spring:
  boot:
    admin:
      client:
        url: http://localhost:8092
  zipkin:
    base-url: http://localhost:9411
  application:
    name: hello-spring-cloud-service-admin

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/