spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  boot:
    admin:
      client:
        url: http://localhost:8092
  zipkin:
    base-url: http://localhost:9411
  application:
    name: hello-spring-cloud-service-admin

server:
  port: 8762

mybatis:
  type-aliases-package: com.wmy.hello.spring.cloud.service.admin.entity
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/